name: 🧪 Create prerelease

on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: Branch to merge into prerelease
        required: true
        default: master
        type: string
      auto_build:
        description: 'Beta-Image nach Deploy automatisch bauen?'
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  merge:
    uses: ./.github/workflows/merge-source-into-branch.yml
    with:
      source-branch: ${{ inputs.source-branch }}
      target-branch: prerelease
      auto_build: ${{ inputs.auto_build == true }}
    secrets: inherit
