name: onOffice WP-Updates Release for testing

on:
    workflow_dispatch:

jobs:
  get-version:
    name: Get current version
    runs-on: ubuntu-latest
    outputs:
      currentVersion: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get version
        id: get-version
        # Remove the leading 'v' from the tag.
        run: echo "version=$(echo ${{ github.ref_name }} | sed -n 's/v\(\)/\1/p')" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: get-version
    uses: ./.github/workflows/build-release.yml
    with:
        expectedVersion: ${{ needs.get-version.outputs.stableVersion }}
        overrideVersion: ${{ needs.get-version.outputs.developmentVersion }}
        checkVersion: false